# Generated by Django 6.0.2 on 2026-02-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_country_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('origin_year', models.IntegerField(default=0)),
                ('is_favourite', models.BooleanField(default=False)),
                ('parent_genres', models.ManyToManyField(blank=True, to='main.genre')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
