# Generated by Django 6.0.2 on 2026-02-27 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='origin_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='parent_genres',
            field=models.ManyToManyField(null=True, to='main.genre'),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True)),
                ('sort_name', models.CharField()),
                ('formation_year', models.IntegerField(null=True)),
                ('closure_year', models.IntegerField(null=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('labelcode', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('BOOTLEGS', 'Bootlegs'), ('DISTRIBUTION', 'Distribution'), ('ORIGINALS', 'Originals'), ('REISSUES', 'Reissues')])),
                ('formation_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
