# Generated by Django 6.0.2 on 2026-02-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_genre_origin_year_alter_genre_parent_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='sort_name',
            field=models.CharField(blank=True),
        ),
    ]
