# Generated by Django 6.0.2 on 2026-02-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_label_sort_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='parent_genres',
            field=models.ManyToManyField(to='main.genre'),
        ),
        migrations.AlterField(
            model_name='label',
            name='closure_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='formation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='labelcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
