# Generated by Django 6.0.2 on 2026-02-27 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_genre_parent_genres_alter_label_closure_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True)),
                ('sort_name', models.CharField(blank=True)),
                ('type', models.CharField(choices=[('GROUP', 'Group'), ('ORCHESTRA', 'Orchestra'), ('OTHER', 'Other'), ('PERSON', 'Person')])),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')])),
                ('formation_year', models.IntegerField(blank=True, null=True)),
                ('disband_year', models.IntegerField(blank=True, null=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('formation_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location')),
                ('genres', models.ManyToManyField(to='main.genre')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
