# Generated by Django 6.0.2 on 2026-02-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_location_name_alter_region_name_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='parent_genres',
            field=models.ManyToManyField(blank=True, to='main.genre'),
        ),
    ]
