# Generated by Django 6.0.2 on 2026-02-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_genre_parent_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('abbreviation', models.CharField(max_length=30)),
                ('classification', models.CharField(choices=[('CARTRIDGE', 'Cartridge'), ('CASSETTE', 'Cassette'), ('DIGITAL', 'Digital'), ('FLASH_DRIVE', 'Flash Drive'), ('MAGNETIC_DISK', 'Magnetic Disk'), ('OPTICAL_DISC', 'Optical Disk'), ('OTHER', 'Other'), ('PHONOGRAPHIC_RECORD', 'Phonographic Record'), ('UNKNOWN', 'Unknown')])),
                ('origin_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
