# Generated by Django 6.0.2 on 2026-02-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',)},
        ),
    ]
