# Generated by Django 6.0.2 on 2026-02-28 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_language_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True)),
                ('sort_name', models.CharField(blank=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')])),
                ('birth_date', models.CharField(default='0000-00-00')),
                ('death_date', models.CharField(blank=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('birth_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
