# Generated by Django 6.0.2 on 2026-03-01 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('catalogue_number', models.CharField(blank=True)),
                ('edition', models.CharField(blank=True)),
                ('is_reissue', models.BooleanField(default=False)),
                ('is_official', models.BooleanField(default=True)),
                ('is_promo', models.BooleanField(default=False)),
                ('has_pregap', models.BooleanField(default=False)),
                ('has_data_track', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=14)),
                ('comment', models.TextField(blank=True)),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.label')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.media')),
                ('release_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.country')),
            ],
            options={
                'ordering': ('catalogue_number',),
            },
        ),
        migrations.CreateModel(
            name='IssueVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_runout', models.CharField(blank=True)),
                ('master_sid', models.CharField(blank=True)),
                ('mould_sid', models.CharField(blank=True)),
                ('spars_code', models.CharField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.issue')),
            ],
            options={
                'ordering': ('matrix_runout',),
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True)),
                ('alternate_title', models.CharField(blank=True)),
                ('release_date', models.CharField(default='0000-00-00')),
                ('is_favourite', models.BooleanField(default=False)),
                ('aoty_rank', models.IntegerField(blank=True, null=True)),
                ('bea_rank', models.IntegerField(blank=True, null=True)),
                ('christgau_rating', models.CharField(blank=True, max_length=5)),
                ('metacritic_rating', models.IntegerField(blank=True, null=True)),
                ('rym_rank', models.IntegerField(blank=True, null=True)),
                ('rym_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_official', models.BooleanField(default=True)),
                ('artists', models.ManyToManyField(to='main.artist')),
                ('genres', models.ManyToManyField(to='main.genre')),
                ('issues', models.ManyToManyField(to='main.issue')),
                ('languages', models.ManyToManyField(to='main.language')),
                ('producers', models.ManyToManyField(to='main.producer')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='parent_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.release'),
        ),
    ]
