# Generated by Django 6.0.2 on 2026-03-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_issue_issuevariant_release_issue_parent_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AUDIOBOOK', 'Audiobook'), ('BROADCAST', 'Broadcast'), ('COMPILATION', 'Compilation'), ('DEMO', 'Demo'), ('DJMIX', 'DJ Mix'), ('EP', 'Extended Play'), ('INTERVIEW', 'Interview'), ('LIVE', 'Live'), ('MIXTAPE', 'Mixtape'), ('OTHER', 'Other'), ('REMIX', 'Remix'), ('SINGLE', 'Single'), ('SOUNDTRACK', 'Soundtrack'), ('STUDIO', 'Studio')])),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.AddField(
            model_name='release',
            name='types',
            field=models.ManyToManyField(to='main.releasetype'),
        ),
    ]
