# Generated by Django 6.0.2 on 2026-03-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_releasetype_release_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='issues',
        ),
    ]
