# Generated by Django 6.0.2 on 2026-03-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_release_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasetype',
            name='type',
            field=models.CharField(unique=True),
        ),
    ]
