# Generated by Django 6.0.2 on 2026-03-01 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_releasetype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='parent_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='main.release'),
        ),
    ]
