# Generated by Django 6.0.2 on 2026-03-01 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_issue_parent_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuevariant',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_variants', to='main.issue'),
        ),
    ]
