# Generated by Django 6.0.2 on 2026-03-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_issuevariant_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasetype',
            name='type',
            field=models.CharField(choices=[('AUDIOBOOK', 'Audiobook'), ('BROADCAST', 'Broadcast'), ('COMPILATION', 'Compilation'), ('DEMO', 'Demo'), ('DJMIX', 'DJ Mix'), ('EP', 'Extended Play'), ('INTERVIEW', 'Interview'), ('LIVE', 'Live'), ('MIXTAPE', 'Mixtape'), ('OTHER', 'Other'), ('REMIX', 'Remix'), ('SINGLE', 'Single'), ('SOUNDTRACK', 'Soundtrack'), ('STUDIO', 'Studio')], unique=True),
        ),
    ]
