# Generated by Django 6.0.2 on 2026-03-02 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_releasetype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='producers',
            field=models.ManyToManyField(blank=True, to='main.producer'),
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_grade', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('MINT', 'Mint'), ('NEARMINT', 'Near Mint'), ('POOR', 'Poor'), ('UNKNOWN', 'Unknown'), ('VERYGOOD', 'Very Good'), ('VERYGOODPLUS', 'Very Good +')])),
                ('packaging_comment', models.TextField(blank=True)),
                ('media_grade', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('MINT', 'Mint'), ('NEARMINT', 'Near Mint'), ('POOR', 'Poor'), ('UNKNOWN', 'Unknown'), ('VERYGOOD', 'Very Good'), ('VERYGOODPLUS', 'Very Good +')])),
                ('media_comment', models.TextField(blank=True)),
                ('is_missing_content', models.BooleanField(default=False)),
                ('missing_content_comment', models.TextField(blank=True)),
                ('has_promo_material', models.BooleanField(default=False)),
                ('remaining_tracks', models.IntegerField(default=0)),
                ('remaining_media_items', models.IntegerField(default=0)),
                ('is_favourite', models.BooleanField(default=False)),
                ('digital_cover_quality', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('POOR', 'Poor'), ('NONE', 'None')], default='NONE')),
                ('backup_state', models.CharField(choices=[('CLEANED', 'Cleaned'), ('DAMAGED', 'Damaged'), ('OTHER', 'Other'), ('RIPPED', 'Ripped'), ('TAGGED', 'Tagged'), ('TODO', 'TODO')])),
                ('comment', models.TextField(blank=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.issue')),
            ],
            options={
                'ordering': ('backup_state',),
            },
        ),
    ]
