# Generated by Django 6.0.2 on 2026-03-07 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_release_producers_collectionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='formation_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, to='main.genre'),
        ),
        migrations.AlterField(
            model_name='media',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
