# Generated by Django 6.0.2 on 2026-03-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_artist_formation_location_alter_artist_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_ref',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
