# Generated by Django 6.0.2 on 2026-03-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_artist_image_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='image_ref',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
