# Generated by Django 6.0.2 on 2026-03-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_label_image_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ('sort_name',)},
        ),
    ]
