# Generated by Django 6.0.2 on 2026-03-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_producer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='image_ref',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
