# Generated by Django 6.0.2 on 2026-05-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_producer_image_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.CharField(default='0000/00/00'),
        ),
    ]
