# Generated by Django 6.0.2 on 2026-05-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_release_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='birth_date',
            field=models.CharField(default='0000/00/00'),
        ),
    ]
